theme: jekyll-theme-cayman
description: "AI in Ethiopia Conference"
basepath: "AiEConf/"
google_analytics: UA-156425047-1

navigation:
- text: HOME
  url: /
- text: EVENTS
  url: /events.md
  layout: default
- text: ORGANIZERS
  url: /organizers.md  
  layout: default
- text: ABOUT
  url: /about.md
  layout: default
