theme: jekyll-theme-slate
description: "AI in Ethiopia Conference"
basepath: "AiEConf/"
google_analytics: UA-156425047-1

navigation:
- text: HOME
  url: /
- text: EVENTS
  url: /events.html
- text: ORGANIZERS
  url: /organizers.html  
- text: DATES
  url: /dates.html
- text: ABOUT
  url: /about.html
